"""Generate tdms_meas_error_3d.ipynb with correct UTF-8 encoding."""
import json

# ─── Cell sources ─────────────────────────────────────────────────────────────

CELL_TITLE_MD = [
    "# PXIe-4080 Raw Measurement Error \u2014 3D Analysis\n",
    "\n",
    "Loads the same TDMS data files as the gain-error notebook, but keeps every\n",
    "individual test-point measurement rather than aggregating to a single gain-error\n",
    "per sweep.  For each sample:\n",
    "\n",
    "```\n",
    "error_ppm = (dut_measurement - source_voltage) / range_voltage * 1_000_000\n",
    "```\n",
    "\n",
    "Exports a single self-contained HTML file (`meas_error_3d.html`) with three\n",
    "interactive Plotly 3D scatter plots:\n",
    "\n",
    "1. **All data** \u2014 10 V and 300 V ranges combined\n",
    "2. **10 V range only**\n",
    "3. **300 V range only**\n",
    "\n",
    "Each plot has one trace per serial number (per range for plot 1).  Use the\n",
    "legend to show/hide individual units.  Use the toolbar buttons to toggle hover\n",
    "or reset the 3D camera.\n",
]

CELL_S1_MD = ["## 1. Imports and filename parser\n"]

CELL_IMPORTS = [
    "import os\n",
    "import re\n",
    "import base64\n",
    "from datetime import datetime\n",
    "\n",
    "import pandas as pd\n",
    "from nptdms import TdmsFile\n",
    "import plotly.graph_objects as go\n",
    "import plotly.colors as pc\n",
    "\n",
    "\n",
    "def parse_filename(filename):\n",
    "    \"\"\"Parse TDMS filename into (serial, temp_set, rh_set, datetime).\n",
    "\n",
    "    Expected pattern (spaces normalised):\n",
    "      <SERIAL>_Temp_Set_<TEMP>_RH_Set_<RH>_MM_DD_YYYY_HH_MM_SS_AM|PM.tdms\n",
    "    \"\"\"\n",
    "    name = filename[:-5].strip()\n",
    "    name = re.sub(r'\\s+', ' ', name)\n",
    "    name = re.sub(r'\\s+(AM|PM)$', r'_\\1', name)\n",
    "    name = name.replace('RH_Set_ ', 'RH_Set_')\n",
    "\n",
    "    pattern = re.compile(\n",
    "        r'^(?P<serial>[^_]+)_Temp_Set_(?P<temp>[^_]+)_RH_Set_(?P<rh>\\d+)_'\n",
    "        r'(?P<month>\\d+)_(?P<day>\\d+)_(?P<year>\\d+)_'\n",
    "        r'(?P<hour>\\d+)_(?P<minute>\\d+)_(?P<second>\\d+)_(?P<am_pm>AM|PM)$'\n",
    "    )\n",
    "    match = pattern.match(name)\n",
    "    if not match:\n",
    "        raise ValueError(f'Unable to parse filename: {filename}')\n",
    "\n",
    "    serial   = match.group('serial')\n",
    "    temp_set = match.group('temp')\n",
    "    rh_set   = match.group('rh')\n",
    "    month    = int(match.group('month'))\n",
    "    day      = int(match.group('day'))\n",
    "    year     = int(match.group('year'))\n",
    "    hour     = int(match.group('hour'))\n",
    "    minute   = int(match.group('minute'))\n",
    "    second   = int(match.group('second'))\n",
    "    am_pm    = match.group('am_pm')\n",
    "\n",
    "    dt = datetime(year, month, day, hour, minute, second)\n",
    "    if am_pm == 'PM' and hour != 12:\n",
    "        dt = dt.replace(hour=hour + 12)\n",
    "    elif am_pm == 'AM' and hour == 12:\n",
    "        dt = dt.replace(hour=0)\n",
    "    return serial, temp_set, rh_set, dt\n",
]

CELL_S2_MD = ["## 2. Helper functions\n"]

CELL_HELPERS = [
    "def serial_sort_key(serial):\n",
    "    \"\"\"Sort hex serial numbers in ascending numeric order.\"\"\"\n",
    "    normalized = str(serial).strip()\n",
    "    if normalized.lower().startswith('0x'):\n",
    "        normalized = normalized[2:]\n",
    "    try:\n",
    "        return (0, int(normalized, 16), str(serial))\n",
    "    except ValueError:\n",
    "        return (1, str(serial))\n",
    "\n",
    "\n",
    "def get_first_available_channel(group, channel_names):\n",
    "    \"\"\"Return data from the first channel name that exists in *group*.\"\"\"\n",
    "    for channel_name in channel_names:\n",
    "        if channel_name in group:\n",
    "            return group[channel_name][:]\n",
    "    joined = ', '.join(channel_names)\n",
    "    raise KeyError(f'No channel found from candidates: {joined}')\n",
    "\n",
    "\n",
    "def inject_branding_header(html_file_path, logo_base64_data):\n",
    "    \"\"\"Insert the NI/Emerson logo and NI Confidential banner after <body>.\"\"\"\n",
    "    with open(html_file_path, 'r', encoding='utf-8') as f:\n",
    "        html_content = f.read()\n",
    "\n",
    "    # Remove any previously injected header block.\n",
    "    html_content = re.sub(\n",
    "        r'<!-- NI_CONFIDENTIAL_HEADER_START -->[\\s\\S]*?<!-- NI_CONFIDENTIAL_HEADER_END -->\\s*',\n",
    "        '',\n",
    "        html_content,\n",
    "        flags=re.IGNORECASE,\n",
    "    )\n",
    "\n",
    "    branding_html = f\"\"\"\n",
    "<!-- NI_CONFIDENTIAL_HEADER_START -->\n",
    "<div id=\\\"ni-confidential-header\\\" style=\\\"padding: 16px 24px 14px; border-bottom: 2px solid #d0d0d0; margin-bottom: 14px; background: #fff;\\\">\n",
    "  <div style=\\\"display: flex; align-items: flex-start; justify-content: space-between;\\\">\n",
    "    <img src=\\\"data:image/jpeg;base64,{logo_base64_data}\\\" alt=\\\"NI/Emerson Logo\\\" style=\\\"height: 58px; width: auto; object-fit: contain;\\\">\n",
    "    <div style=\\\"flex: 1; text-align: center; margin-right: 58px;\\\">\n",
    "      <h1 style=\\\"color: #c62828; font-size: 24px; margin: 0 0 8px 0; font-weight: 700;\\\">NI Confidential</h1>\n",
    "      <p style=\\\"color: #111; font-size: 14px; margin: 0; line-height: 1.35;\\\">\n",
    "        This document contains proprietary information of NI/Emerson and is intended for internal use only. Unauthorized distribution is prohibited.\n",
    "      </p>\n",
    "    </div>\n",
    "  </div>\n",
    "</div>\n",
    "<!-- NI_CONFIDENTIAL_HEADER_END -->\n",
    "\\\"\\\"\\\"\n",
    "\n",
    "    body_match = re.search(r'<body[^>]*>', html_content, flags=re.IGNORECASE)\n",
    "    if body_match:\n",
    "        insert_at = body_match.end()\n",
    "        html_content = html_content[:insert_at] + '\\n' + branding_html + '\\n' + html_content[insert_at:]\n",
    "    else:\n",
    "        html_content = branding_html + '\\n' + html_content\n",
    "\n",
    "    with open(html_file_path, 'w', encoding='utf-8') as f:\n",
    "        f.write(html_content)\n",
]

CELL_S3_MD = [
    "## 3. Configuration\n",
    "\n",
    "Set `ROOT_PATH` to the folder containing one sub-folder per DUT serial number.\n",
    "Each sub-folder should hold the `.tdms` files for that unit.\n",
]

CELL_CONFIG = [
    "ROOT_PATH   = r'C:\\temp\\EnvironmentalTesting\\Round2Data'\n",
    "OUTPUT_HTML = 'meas_error_3d.html'\n",
    "\n",
    "# Divisor for PPM conversion: error_ppm = (dut - src) / divisor * 1_000_000\n",
    "RANGE_DIVISORS = {'10V': 10.0, '300V': 300.0}\n",
    "\n",
    "# ---- logo ----\n",
    "LOGO_PATH = 'NI-Emerson.jpg'\n",
    "with open(LOGO_PATH, 'rb') as f:\n",
    "    LOGO_BASE64 = base64.b64encode(f.read()).decode('utf-8')\n",
    "print(f'Logo loaded and encoded ({len(LOGO_BASE64)} bytes base64 data)')\n",
]

CELL_S4_MD = [
    "## 4. Load TDMS data\n",
    "\n",
    "Walks each serial sub-folder, reads the `Test Points` and `DUT Measurements`\n",
    "channels for the 10 V and 300 V ranges, and expands every sweep into individual\n",
    "per-test-point rows.  The measurement error is converted to PPM of range.\n",
]

CELL_LOAD = [
    "data = []\n",
    "\n",
    "if not os.path.exists(ROOT_PATH):\n",
    "    raise FileNotFoundError(f'Path not found: {ROOT_PATH}  \u2014 please update ROOT_PATH.')\n",
    "\n",
    "# Collect every .tdms file up front so we can report progress while loading.\n",
    "tdms_files = []\n",
    "for subdir in os.listdir(ROOT_PATH):\n",
    "    serial_path = os.path.join(ROOT_PATH, subdir)\n",
    "    if not os.path.isdir(serial_path):\n",
    "        continue\n",
    "    for file in os.listdir(serial_path):\n",
    "        if file.endswith('.tdms'):\n",
    "            tdms_files.append((serial_path, file))\n",
    "\n",
    "total_files = len(tdms_files)\n",
    "print(f'Found {total_files} TDMS file(s) to process.')\n",
    "\n",
    "for idx, (serial_path, file) in enumerate(tdms_files, start=1):\n",
    "    print(f'\\r[{idx}/{total_files}] Loading {file[:60]}', end='', flush=True)\n",
    "    filepath = os.path.join(serial_path, file)\n",
    "    try:\n",
    "        parsed_serial, temp_set, rh_set, timestamp = parse_filename(file)\n",
    "        tdms_file = TdmsFile.read(filepath)\n",
    "        group = tdms_file.groups()[0]\n",
    "\n",
    "        ranges_config = [\n",
    "            ('10V',  ['Test Points 10V'],                ['DUT Measurements 10V']),\n",
    "            ('300V', ['Test Points 300V', 'Test Points'], ['DUT Measurements 300V', 'DUT Measurements']),\n",
    "        ]\n",
    "\n",
    "        for range_name, test_candidates, dut_candidates in ranges_config:\n",
    "            test_col = next((c for c in test_candidates if c in group), None)\n",
    "            dut_col  = next((c for c in dut_candidates  if c in group), None)\n",
    "            if test_col is None or dut_col is None:\n",
    "                continue\n",
    "\n",
    "            test_pts = group[test_col][:]\n",
    "            dut_meas = group[dut_col][:]\n",
    "            divisor  = RANGE_DIVISORS[range_name]\n",
    "\n",
    "            for src, dut in zip(test_pts, dut_meas):\n",
    "                error_ppm = (float(dut) - float(src)) / divisor * 1_000_000\n",
    "                data.append({\n",
    "                    'timestamp':      timestamp,\n",
    "                    'serial':         parsed_serial,\n",
    "                    'range':          range_name,\n",
    "                    'source_voltage': float(src),\n",
    "                    'meas_error_ppm': error_ppm,\n",
    "                })\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f'\\nError processing {filepath}: {e}')\n",
    "\n",
    "print(f'\\nDone. Loaded {len(data):,} sample(s) from {total_files} file(s).')\n",
    "\n",
    "df = pd.DataFrame(data)\n",
    "if df.empty:\n",
    "    raise ValueError('No data loaded \u2014 check ROOT_PATH and TDMS file names.')\n",
    "\n",
    "df = df.sort_values(['serial', 'timestamp', 'source_voltage']).reset_index(drop=True)\n",
    "\n",
    "summary = df.groupby(['serial', 'range']).agg(\n",
    "    sweeps=('timestamp', 'nunique'),\n",
    "    samples=('meas_error_ppm', 'count')\n",
    ")\n",
    "print('\\nData summary (sweeps = unique timestamps):')\n",
    "print(summary.to_string())\n",
]

CELL_S5_MD = [
    "## 5. Build 3D plots and export HTML\n",
    "\n",
    "Three interactive Plotly 3D scatter plots are assembled and exported to a single\n",
    "self-contained HTML file.\n",
    "\n",
    "* **X axis** \u2014 sweep date / time\n",
    "* **Y axis** \u2014 source voltage (V)\n",
    "* **Z axis** \u2014 measurement error (PPM of range)\n",
    "\n",
    "Each sweep appears as a vertical \"curtain\" of points showing the full error\n",
    "profile across all test-point voltages at that moment in time.\n",
]

CELL_PLOTS = [
    "if df.empty:\n",
    "    raise ValueError('No data loaded. Run the data-loading cell first.')\n",
    "\n",
    "# ── Colour palette: one consistent colour per serial across all three plots ──\n",
    "serials = sorted(df['serial'].unique(), key=serial_sort_key)\n",
    "palette = pc.qualitative.Plotly + pc.qualitative.D3 + pc.qualitative.G10\n",
    "serial_colors = {ser: palette[idx % len(palette)] for idx, ser in enumerate(serials)}\n",
    "\n",
    "# ── Shared 3D scene axis titles ──\n",
    "SCENE_LAYOUT = dict(\n",
    "    xaxis=dict(title='Sweep Date / Time'),\n",
    "    yaxis=dict(title='Source Voltage (V)'),\n",
    "    zaxis=dict(title='Measurement Error (PPM)'),\n",
    ")\n",
    "\n",
    "\n",
    "def make_3d_buttons():\n",
    "    \"\"\"Toolbar buttons: hover toggle and reset-view for a 3D figure.\"\"\"\n",
    "    return [\n",
    "        dict(\n",
    "            type='buttons',\n",
    "            direction='left',\n",
    "            buttons=[\n",
    "                dict(\n",
    "                    label='Hover: On',\n",
    "                    method='relayout',\n",
    "                    args=[{'hovermode': 'closest'}],\n",
    "                ),\n",
    "                dict(\n",
    "                    label='Hover: Off',\n",
    "                    method='relayout',\n",
    "                    args=[{'hovermode': False}],\n",
    "                ),\n",
    "                dict(\n",
    "                    label='Reset View',\n",
    "                    method='relayout',\n",
    "                    args=[{'scene.camera.eye': {'x': 1.25, 'y': 1.25, 'z': 1.25}}],\n",
    "                ),\n",
    "            ],\n",
    "            pad={'r': 10, 't': 10},\n",
    "            showactive=True,\n",
    "            x=0.0,\n",
    "            xanchor='left',\n",
    "            y=1.05,\n",
    "            yanchor='top',\n",
    "        )\n",
    "    ]\n",
    "\n",
    "\n",
    "def make_trace(sub_df, trace_name, color):\n",
    "    \"\"\"Return a go.Scatter3d trace for *sub_df* rows.\"\"\"\n",
    "    return go.Scatter3d(\n",
    "        x=sub_df['timestamp'],\n",
    "        y=sub_df['source_voltage'],\n",
    "        z=sub_df['meas_error_ppm'],\n",
    "        mode='markers',\n",
    "        name=trace_name,\n",
    "        marker=dict(size=2, color=color, opacity=0.7),\n",
    "        hovertemplate=(\n",
    "            '<b>' + trace_name + '</b><br>'\n",
    "            'Time: %{x}<br>'\n",
    "            'Source: %{y:.4f} V<br>'\n",
    "            'Error: %{z:.3f} ppm<extra></extra>'\n",
    "        ),\n",
    "    )\n",
    "\n",
    "\n",
    "# ── Figure 1: All data (10V + 300V combined) ──────────────────────────────────\n",
    "fig_all = go.Figure()\n",
    "for ser in serials:\n",
    "    ser_df = df[df['serial'] == ser]\n",
    "    for range_name in ('10V', '300V'):\n",
    "        rd = ser_df[ser_df['range'] == range_name]\n",
    "        if rd.empty:\n",
    "            continue\n",
    "        fig_all.add_trace(make_trace(rd, f'{ser} {range_name}', serial_colors[ser]))\n",
    "\n",
    "fig_all.update_layout(\n",
    "    title='PXIe-4080 Measurement Error \u2014 All Ranges (10V + 300V)',\n",
    "    autosize=True,\n",
    "    hovermode='closest',\n",
    "    scene=SCENE_LAYOUT,\n",
    "    legend=dict(x=0, y=1, bgcolor='rgba(255,255,255,0.6)'),\n",
    "    updatemenus=make_3d_buttons(),\n",
    ")\n",
    "\n",
    "# ── Figure 2: 10V range only ───────────────────────────────────────────────────\n",
    "fig_10v = go.Figure()\n",
    "for ser in serials:\n",
    "    sd = df[(df['serial'] == ser) & (df['range'] == '10V')]\n",
    "    if sd.empty:\n",
    "        continue\n",
    "    fig_10v.add_trace(make_trace(sd, ser, serial_colors[ser]))\n",
    "\n",
    "fig_10v.update_layout(\n",
    "    title='PXIe-4080 Measurement Error \u2014 10V Range',\n",
    "    autosize=True,\n",
    "    hovermode='closest',\n",
    "    scene=SCENE_LAYOUT,\n",
    "    legend=dict(x=0, y=1, bgcolor='rgba(255,255,255,0.6)'),\n",
    "    updatemenus=make_3d_buttons(),\n",
    ")\n",
    "\n",
    "# ── Figure 3: 300V range only ──────────────────────────────────────────────────\n",
    "fig_300v = go.Figure()\n",
    "for ser in serials:\n",
    "    sd = df[(df['serial'] == ser) & (df['range'] == '300V')]\n",
    "    if sd.empty:\n",
    "        continue\n",
    "    fig_300v.add_trace(make_trace(sd, ser, serial_colors[ser]))\n",
    "\n",
    "fig_300v.update_layout(\n",
    "    title='PXIe-4080 Measurement Error \u2014 300V Range',\n",
    "    autosize=True,\n",
    "    hovermode='closest',\n",
    "    scene=SCENE_LAYOUT,\n",
    "    legend=dict(x=0, y=1, bgcolor='rgba(255,255,255,0.6)'),\n",
    "    updatemenus=make_3d_buttons(),\n",
    ")\n",
    "\n",
    "# ── Render each figure to an HTML div ─────────────────────────────────────────\n",
    "# First figure embeds the full plotly.js library; subsequent ones reuse it.\n",
    "div_all  = fig_all.to_html(\n",
    "    full_html=False, include_plotlyjs=True, div_id='plot_all',\n",
    "    default_width='100%', default_height='700px',\n",
    "    config={'responsive': True},\n",
    ")\n",
    "div_10v  = fig_10v.to_html(\n",
    "    full_html=False, include_plotlyjs=False, div_id='plot_10v',\n",
    "    default_width='100%', default_height='700px',\n",
    "    config={'responsive': True},\n",
    ")\n",
    "div_300v = fig_300v.to_html(\n",
    "    full_html=False, include_plotlyjs=False, div_id='plot_300v',\n",
    "    default_width='100%', default_height='700px',\n",
    "    config={'responsive': True},\n",
    ")\n",
    "\n",
    "# ── Assemble combined HTML page ────────────────────────────────────────────────\n",
    "# Single-quoted HTML attributes inside triple-single-quoted Python strings:\n",
    "# no JSON-encoding issues and valid HTML5.\n",
    "HEADER_HTML = (\n",
    "    \"<!DOCTYPE html>\\n\"\n",
    "    \"<html lang='en'>\\n\"\n",
    "    \"<head>\\n\"\n",
    "    \"  <meta charset='utf-8'>\\n\"\n",
    "    \"  <meta name='viewport' content='width=device-width, initial-scale=1'>\\n\"\n",
    "    \"  <title>PXIe-4080 Measurement Error 3D Analysis</title>\\n\"\n",
    "    \"  <style>\\n\"\n",
    "    \"    body {font-family: Arial, Helvetica, sans-serif; margin: 0; padding: 0; background: #f0f0f0;}\\n\"\n",
    "    \"    .plot-section {\\n\"\n",
    "    \"      background: #ffffff;\\n\"\n",
    "    \"      margin: 14px 16px;\\n\"\n",
    "    \"      padding: 14px 16px 8px;\\n\"\n",
    "    \"      border-radius: 4px;\\n\"\n",
    "    \"      box-shadow: 0 1px 4px rgba(0,0,0,0.12);\\n\"\n",
    "    \"    }\\n\"\n",
    "    \"    .plot-section h2 {color: #1a1a1a; font-size: 16px; margin: 0 0 8px 0; font-weight: 600;}\\n\"\n",
    "    \"  </style>\\n\"\n",
    "    \"</head>\\n\"\n",
    "    \"<body>\\n\"\n",
    "    \"  <div class='plot-section'>\\n\"\n",
    "    \"    <h2>All Ranges &#8212; 10V and 300V Measurement Error vs. Time and Source Voltage</h2>\\n\"\n",
    ")\n",
    "\n",
    "MID1_HTML = (\n",
    "    \"  </div>\\n\"\n",
    "    \"  <div class='plot-section'>\\n\"\n",
    "    \"    <h2>10V Range &#8212; Measurement Error vs. Time and Source Voltage</h2>\\n\"\n",
    ")\n",
    "\n",
    "MID2_HTML = (\n",
    "    \"  </div>\\n\"\n",
    "    \"  <div class='plot-section'>\\n\"\n",
    "    \"    <h2>300V Range &#8212; Measurement Error vs. Time and Source Voltage</h2>\\n\"\n",
    ")\n",
    "\n",
    "FOOTER_HTML = (\n",
    "    \"  </div>\\n\"\n",
    "    \"</body>\\n\"\n",
    "    \"</html>\\n\"\n",
    ")\n",
    "\n",
    "html_page = HEADER_HTML + div_all + MID1_HTML + div_10v + MID2_HTML + div_300v + FOOTER_HTML\n",
    "\n",
    "with open(OUTPUT_HTML, 'w', encoding='utf-8') as f:\n",
    "    f.write(html_page)\n",
    "\n",
    "inject_branding_header(OUTPUT_HTML, LOGO_BASE64)\n",
    "\n",
    "print(f'HTML written to {OUTPUT_HTML}')\n",
    "print(f'  {len(data):,} samples  |  {len(serials)} serial(s)  |  {len(tdms_files)} TDMS file(s)')\n",
    "\n",
    "fig_all.show()\n",
]

# ─── Assemble notebook ────────────────────────────────────────────────────────

def code_cell(cid, source):
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": cid,
        "metadata": {},
        "outputs": [],
        "source": source,
    }

def md_cell(cid, source):
    return {
        "cell_type": "markdown",
        "id": cid,
        "metadata": {},
        "source": source,
    }

nb = {
    "cells": [
        md_cell("m0001", CELL_TITLE_MD),
        md_cell("m0002", CELL_S1_MD),
        code_cell("c0001", CELL_IMPORTS),
        md_cell("m0003", CELL_S2_MD),
        code_cell("c0002", CELL_HELPERS),
        md_cell("m0004", CELL_S3_MD),
        code_cell("c0003", CELL_CONFIG),
        md_cell("m0005", CELL_S4_MD),
        code_cell("c0004", CELL_LOAD),
        md_cell("m0006", CELL_S5_MD),
        code_cell("c0005", CELL_PLOTS),
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "pygments_lexer": "ipython3",
            "version": "3.9.0",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

OUTPUT = "tdms_meas_error_3d.ipynb"
with open(OUTPUT, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

print(f"Written {OUTPUT}  ({len(nb['cells'])} cells)")
